CI: Update docker compose command.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,11 +49,11 @@ jobs:
             git reset --hard origin/$BRANCH || { echo "Git reset failed. Exiting."; exit 1; }
 
             echo "Building Docker containers..."
-            docker-compose -f docker-compose.prod.yml build || { echo "Docker build failed. Exiting."; exit 1; }
+            docker compose -f docker-compose.prod.yml build || { echo "Docker build failed. Exiting."; exit 1; }
 
             echo "Restarting Docker services..."
-            docker-compose -f docker-compose.prod.yml down || { echo "Docker shutdown failed. Exiting."; exit 1; }
-            docker-compose -f docker-compose.prod.yml up -d || { echo "Docker startup failed. Exiting."; exit 1; }
+            docker compose -f docker-compose.prod.yml down || { echo "Docker shutdown failed. Exiting."; exit 1; }
+            docker compose -f docker-compose.prod.yml up -d || { echo "Docker startup failed. Exiting."; exit 1; }
             
             # Run compilemessages
             echo "Compiling messages..."
