fix(deploy): update Docker commands to use docker compose for better compatibility

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -58,24 +58,24 @@ jobs:
             
             # Run compilemessages
             echo "Compiling messages..."
-            docker exec chat-app python manage.py compilemessages || { echo "Compilemessages failed. Exiting."; exit 1; }
+            docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T chat-app python manage.py compilemessages || { echo "Compilemessages failed. Exiting."; exit 1; }
             
             # Clear Redis if input is True
             if [ "$CLEAR_REDIS" = "true" ]; then
               echo "Clearing Redis database..."
-              docker exec redis redis-cli -a $REDIS_PASSWORD FLUSHALL || { echo "Redis clearing failed. Exiting."; exit 1; }
+              docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T my-redis redis-cli -a $REDIS_PASSWORD FLUSHALL || { echo "Redis clearing failed. Exiting."; exit 1; }
             fi
             
             # Run migrations if input is true
             if [ "$RUN_MIGRATIONS" = "true" ]; then
               echo "Running database migrations..."
-              docker exec chat-app python manage.py migrate --noinput || { echo "Database migrations failed. Exiting."; exit 1; }
+              docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T chat-app python manage.py migrate --noinput || { echo "Database migrations failed. Exiting."; exit 1; }
             fi
             
             # Run collectstatic if input is true
             if [ "$RUN_COLLECTSTATIC" = "true" ]; then
               echo "Collecting static files..."
-              docker exec chat-app python manage.py collectstatic --noinput || { echo "Collectstatic failed. Exiting."; exit 1; }
+              docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T chat-app python manage.py collectstatic --noinput || { echo "Collectstatic failed. Exiting."; exit 1; }
             fi
 
             echo "Restarting NGINX..."
